### ISSUE TITLE
[FR] Cancel reducing the blurriness of unactivated tabs and switch to highlighting the activated tabs

### ISSUE THREAD

**Issue by wwjCMP** [hdykokd/obsidian-vertical-tabs-view#39]
Cancel reducing the blurriness of unactivated tabs and switch to highlighting the activated tabs.

**Comment by hdykokd** [comment]
Sorry for the lack of my design skills. I'd like to make it better.

**Comment by hdykokd** [comment]
Ah, I understood the problem. I may have reversed the styles applied to active and inactive tabs.

**Comment by hdykokd** [comment]
https://docs.obsidian.md/Reference/CSS+variables/Components/Tabs

I had already designed a style to apply to the active tab like this.

```css
.vertical-tabs-view-list li.focused {
  color: var(--tab-text-color-focused-active-current);
  background-color: var(--tab-background-active);
}
```

It may be due to the theme you are using or the styles you have applied independently.
In fact, it works well with the default theme. However, with the AnuPpuccin theme that I usually use, it doesn't look as good.
(In the AnuPpuccin theme, using color: var(--color-accent); makes it look elegant. Personally, I'm starting to feel that this is better.)

Ideally, as mentioned in https://github.com/hdykokd/obsidian-vertical-tabs-view/issues/45#issuecomment-1783688048, it would be great to have finer-grained customization options, but it might take some time. For now, I believe it's a good idea to override the styles on your own.
