### ISSUE TITLE
Feature request: Highlight active tab

### ISSUE THREAD

**Issue by Rhydderch** [hdykokd/obsidian-vertical-tabs-view#71]
Hi,
Would it be possible to style differently the current active tab?

**Comment by hdykokd** [comment]
Maybe you want to apply a style that suits your taste?
Obsidian has features for customizing styles. Try assigning style to the active tab class.

**Comment by yuscale** [comment]
just try this snippet
```css
.is-focused .vertical-tabs-view-list li.focused,
.vertical-tabs-view-list li.focused {
    color:navy;
    background-color:honeydew;
}
```
